version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:13.3"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "student"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1111"
      PGDATA: "/var/lib/postgresql/data/pgdata"